version: "3.8"

services:
  replica1:
    build: ./replica
    container_name: replica1
    environment:
      REPLICA_ID: "1"
      PORT: "5001"
      PEERS: "http://replica2:5002,http://replica3:5003"
    ports:
      - "5001:5001"
    networks:
      - raftnet

  replica2:
    build: ./replica
    container_name: replica2
    environment:
      REPLICA_ID: "2"
      PORT: "5002"
      PEERS: "http://replica1:5001,http://replica3:5003"
    ports:
      - "5002:5002"
    networks:
      - raftnet

  replica3:
    build: ./replica
    container_name: replica3
    environment:
      REPLICA_ID: "3"
      PORT: "5003"
      PEERS: "http://replica1:5001,http://replica2:5002"
    ports:
      - "5003:5003"
    networks:
      - raftnet

networks:
  raftnet:
    driver: bridge